// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: cmd_trailer.proto

package baseproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CmdTrailer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CmdTrailer) Reset() {
	*x = CmdTrailer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_trailer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdTrailer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdTrailer) ProtoMessage() {}

func (x *CmdTrailer) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_trailer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdTrailer.ProtoReflect.Descriptor instead.
func (*CmdTrailer) Descriptor() ([]byte, []int) {
	return file_cmd_trailer_proto_rawDescGZIP(), []int{0}
}

var File_cmd_trailer_proto protoreflect.FileDescriptor

var file_cmd_trailer_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6d, 0x64, 0x5f, 0x74, 0x72, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f,
	0x75, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x22, 0x0c, 0x0a, 0x0a, 0x43, 0x6d, 0x64, 0x54, 0x72,
	0x61, 0x69, 0x6c, 0x65, 0x72, 0x42, 0x3c, 0x50, 0x01, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x6d, 0x6e, 0x61, 0x74, 0x68, 0x36, 0x37, 0x36,
	0x34, 0x33, 0x2f, 0x61, 0x75, 0x72, 0x6f, 0x72, 0x61, 0x2d, 0x73, 0x69, 0x7a, 0x69, 0x6e, 0x67,
	0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x67, 0x6f, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_trailer_proto_rawDescOnce sync.Once
	file_cmd_trailer_proto_rawDescData = file_cmd_trailer_proto_rawDesc
)

func file_cmd_trailer_proto_rawDescGZIP() []byte {
	file_cmd_trailer_proto_rawDescOnce.Do(func() {
		file_cmd_trailer_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_trailer_proto_rawDescData)
	})
	return file_cmd_trailer_proto_rawDescData
}

var file_cmd_trailer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cmd_trailer_proto_goTypes = []interface{}{
	(*CmdTrailer)(nil), // 0: org.anonymous.grpc.CmdTrailer
}
var file_cmd_trailer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_trailer_proto_init() }
func file_cmd_trailer_proto_init() {
	if File_cmd_trailer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_trailer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdTrailer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_trailer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_trailer_proto_goTypes,
		DependencyIndexes: file_cmd_trailer_proto_depIdxs,
		MessageInfos:      file_cmd_trailer_proto_msgTypes,
	}.Build()
	File_cmd_trailer_proto = out.File
	file_cmd_trailer_proto_rawDesc = nil
	file_cmd_trailer_proto_goTypes = nil
	file_cmd_trailer_proto_depIdxs = nil
}
