// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: cmd_lookup_by_name.proto

package baseproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CmdLookupByName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageSize        int32   `protobuf:"varint,1,opt,name=message_size,json=messageSize,proto3" json:"message_size,omitempty"`
	MessageType        CmdType `protobuf:"varint,2,opt,name=message_type,json=messageType,proto3,enum=org.anonymous.grpc.CmdType" json:"message_type,omitempty"`
	GetType            GetType `protobuf:"varint,3,opt,name=get_type,json=getType,proto3,enum=org.anonymous.grpc.GetType" json:"get_type,omitempty"`
	Count              int32   `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	SecurityNamePrefix string  `protobuf:"bytes,5,opt,name=security_name_prefix,json=securityNamePrefix,proto3" json:"security_name_prefix,omitempty"`
}

func (x *CmdLookupByName) Reset() {
	*x = CmdLookupByName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_lookup_by_name_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdLookupByName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdLookupByName) ProtoMessage() {}

func (x *CmdLookupByName) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_lookup_by_name_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdLookupByName.ProtoReflect.Descriptor instead.
func (*CmdLookupByName) Descriptor() ([]byte, []int) {
	return file_cmd_lookup_by_name_proto_rawDescGZIP(), []int{0}
}

func (x *CmdLookupByName) GetMessageSize() int32 {
	if x != nil {
		return x.MessageSize
	}
	return 0
}

func (x *CmdLookupByName) GetMessageType() CmdType {
	if x != nil {
		return x.MessageType
	}
	return CmdType_CMD_UNDEFINED
}

func (x *CmdLookupByName) GetGetType() GetType {
	if x != nil {
		return x.GetType
	}
	return GetType_SDB_GET_FIRST
}

func (x *CmdLookupByName) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CmdLookupByName) GetSecurityNamePrefix() string {
	if x != nil {
		return x.SecurityNamePrefix
	}
	return ""
}

type CmdLookupByNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageSize   int32    `protobuf:"varint,1,opt,name=message_size,json=messageSize,proto3" json:"message_size,omitempty"`
	SecurityCount int32    `protobuf:"varint,2,opt,name=security_count,json=securityCount,proto3" json:"security_count,omitempty"`
	SecurityNames []string `protobuf:"bytes,3,rep,name=security_names,json=securityNames,proto3" json:"security_names,omitempty"`
}

func (x *CmdLookupByNameResponse) Reset() {
	*x = CmdLookupByNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_lookup_by_name_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdLookupByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdLookupByNameResponse) ProtoMessage() {}

func (x *CmdLookupByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_lookup_by_name_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdLookupByNameResponse.ProtoReflect.Descriptor instead.
func (*CmdLookupByNameResponse) Descriptor() ([]byte, []int) {
	return file_cmd_lookup_by_name_proto_rawDescGZIP(), []int{1}
}

func (x *CmdLookupByNameResponse) GetMessageSize() int32 {
	if x != nil {
		return x.MessageSize
	}
	return 0
}

func (x *CmdLookupByNameResponse) GetSecurityCount() int32 {
	if x != nil {
		return x.SecurityCount
	}
	return 0
}

func (x *CmdLookupByNameResponse) GetSecurityNames() []string {
	if x != nil {
		return x.SecurityNames
	}
	return nil
}

var File_cmd_lookup_by_name_proto protoreflect.FileDescriptor

var file_cmd_lookup_by_name_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x6d, 0x64, 0x5f, 0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x5f, 0x62, 0x79, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6f, 0x72, 0x67, 0x2e,
	0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x0e,
	0x63, 0x6d, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e,
	0x67, 0x65, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf4,
	0x01, 0x0a, 0x0f, 0x43, 0x6d, 0x64, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x42, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x3e, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6f, 0x72,
	0x67, 0x2e, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x43, 0x6d, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x67, 0x65, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x6e,
	0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x67, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x14, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x12, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x50,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x22, 0x8a, 0x01, 0x0a, 0x17, 0x43, 0x6d, 0x64, 0x4c, 0x6f, 0x6f,
	0x6b, 0x75, 0x70, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x73, 0x65,
	0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x73,
	0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x42, 0x3c, 0x50, 0x01, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x6d, 0x6e, 0x61, 0x74, 0x68, 0x36, 0x37, 0x36, 0x34, 0x33, 0x2f,
	0x61, 0x75, 0x72, 0x6f, 0x72, 0x61, 0x2d, 0x73, 0x69, 0x7a, 0x69, 0x6e, 0x67, 0x2f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x67, 0x6f, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_lookup_by_name_proto_rawDescOnce sync.Once
	file_cmd_lookup_by_name_proto_rawDescData = file_cmd_lookup_by_name_proto_rawDesc
)

func file_cmd_lookup_by_name_proto_rawDescGZIP() []byte {
	file_cmd_lookup_by_name_proto_rawDescOnce.Do(func() {
		file_cmd_lookup_by_name_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_lookup_by_name_proto_rawDescData)
	})
	return file_cmd_lookup_by_name_proto_rawDescData
}

var file_cmd_lookup_by_name_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cmd_lookup_by_name_proto_goTypes = []interface{}{
	(*CmdLookupByName)(nil),         // 0: org.anonymous.grpc.CmdLookupByName
	(*CmdLookupByNameResponse)(nil), // 1: org.anonymous.grpc.CmdLookupByNameResponse
	(CmdType)(0),                    // 2: org.anonymous.grpc.CmdType
	(GetType)(0),                    // 3: org.anonymous.grpc.GetType
}
var file_cmd_lookup_by_name_proto_depIdxs = []int32{
	2, // 0: org.anonymous.grpc.CmdLookupByName.message_type:type_name -> org.anonymous.grpc.CmdType
	3, // 1: org.anonymous.grpc.CmdLookupByName.get_type:type_name -> org.anonymous.grpc.GetType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cmd_lookup_by_name_proto_init() }
func file_cmd_lookup_by_name_proto_init() {
	if File_cmd_lookup_by_name_proto != nil {
		return
	}
	file_cmd_type_proto_init()
	file_get_type_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cmd_lookup_by_name_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdLookupByName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_lookup_by_name_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdLookupByNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_lookup_by_name_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_lookup_by_name_proto_goTypes,
		DependencyIndexes: file_cmd_lookup_by_name_proto_depIdxs,
		MessageInfos:      file_cmd_lookup_by_name_proto_msgTypes,
	}.Build()
	File_cmd_lookup_by_name_proto = out.File
	file_cmd_lookup_by_name_proto_rawDesc = nil
	file_cmd_lookup_by_name_proto_goTypes = nil
	file_cmd_lookup_by_name_proto_depIdxs = nil
}
