// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: cmd_header.proto

package baseproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CmdHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransName     string `protobuf:"bytes,1,opt,name=trans_name,json=transName,proto3" json:"trans_name,omitempty"`
	SecType       uint32 `protobuf:"varint,2,opt,name=sec_type,json=secType,proto3" json:"sec_type,omitempty"`
	TransType     uint32 `protobuf:"varint,3,opt,name=trans_type,json=transType,proto3" json:"trans_type,omitempty"`
	DbId          uint32 `protobuf:"varint,4,opt,name=db_id,json=dbId,proto3" json:"db_id,omitempty"`
	DetailParts   uint32 `protobuf:"varint,5,opt,name=detail_parts,json=detailParts,proto3" json:"detail_parts,omitempty"`
	SourceTransId uint32 `protobuf:"varint,6,opt,name=source_trans_id,json=sourceTransId,proto3" json:"source_trans_id,omitempty"`
	TransFlags    int32  `protobuf:"varint,7,opt,name=trans_flags,json=transFlags,proto3" json:"trans_flags,omitempty"`
}

func (x *CmdHeader) Reset() {
	*x = CmdHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_header_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdHeader) ProtoMessage() {}

func (x *CmdHeader) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_header_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdHeader.ProtoReflect.Descriptor instead.
func (*CmdHeader) Descriptor() ([]byte, []int) {
	return file_cmd_header_proto_rawDescGZIP(), []int{0}
}

func (x *CmdHeader) GetTransName() string {
	if x != nil {
		return x.TransName
	}
	return ""
}

func (x *CmdHeader) GetSecType() uint32 {
	if x != nil {
		return x.SecType
	}
	return 0
}

func (x *CmdHeader) GetTransType() uint32 {
	if x != nil {
		return x.TransType
	}
	return 0
}

func (x *CmdHeader) GetDbId() uint32 {
	if x != nil {
		return x.DbId
	}
	return 0
}

func (x *CmdHeader) GetDetailParts() uint32 {
	if x != nil {
		return x.DetailParts
	}
	return 0
}

func (x *CmdHeader) GetSourceTransId() uint32 {
	if x != nil {
		return x.SourceTransId
	}
	return 0
}

func (x *CmdHeader) GetTransFlags() int32 {
	if x != nil {
		return x.TransFlags
	}
	return 0
}

var File_cmd_header_proto protoreflect.FileDescriptor

var file_cmd_header_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6d, 0x64, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x12, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75,
	0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x22, 0xe5, 0x01, 0x0a, 0x09, 0x43, 0x6d, 0x64, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x65, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x65, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a,
	0x05, 0x64, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x64, 0x62,
	0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x5f, 0x70, 0x61, 0x72,
	0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x50, 0x61, 0x72, 0x74, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x42, 0x3c,
	0x50, 0x01, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73,
	0x6f, 0x6d, 0x6e, 0x61, 0x74, 0x68, 0x36, 0x37, 0x36, 0x34, 0x33, 0x2f, 0x61, 0x75, 0x72, 0x6f,
	0x72, 0x61, 0x2d, 0x73, 0x69, 0x7a, 0x69, 0x6e, 0x67, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x67, 0x6f, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_header_proto_rawDescOnce sync.Once
	file_cmd_header_proto_rawDescData = file_cmd_header_proto_rawDesc
)

func file_cmd_header_proto_rawDescGZIP() []byte {
	file_cmd_header_proto_rawDescOnce.Do(func() {
		file_cmd_header_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_header_proto_rawDescData)
	})
	return file_cmd_header_proto_rawDescData
}

var file_cmd_header_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cmd_header_proto_goTypes = []interface{}{
	(*CmdHeader)(nil), // 0: org.anonymous.grpc.CmdHeader
}
var file_cmd_header_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_header_proto_init() }
func file_cmd_header_proto_init() {
	if File_cmd_header_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_header_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_header_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_header_proto_goTypes,
		DependencyIndexes: file_cmd_header_proto_depIdxs,
		MessageInfos:      file_cmd_header_proto_msgTypes,
	}.Build()
	File_cmd_header_proto = out.File
	file_cmd_header_proto_rawDesc = nil
	file_cmd_header_proto_goTypes = nil
	file_cmd_header_proto_depIdxs = nil
}
