// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: cmd_get_many_by_name_ext.proto

package baseproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CmdGetManyByNameExt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType    CmdType  `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=org.anonymous.grpc.CmdType" json:"message_type,omitempty"`
	MessageVersion int32    `protobuf:"varint,2,opt,name=message_version,json=messageVersion,proto3" json:"message_version,omitempty"`
	ArgumentFlags  int32    `protobuf:"varint,3,opt,name=argument_flags,json=argumentFlags,proto3" json:"argument_flags,omitempty"`
	MaxTradeIds    int32    `protobuf:"varint,4,opt,name=max_trade_ids,json=maxTradeIds,proto3" json:"max_trade_ids,omitempty"`
	Count          uint32   `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	SecurityNames  []string `protobuf:"bytes,6,rep,name=security_names,json=securityNames,proto3" json:"security_names,omitempty"`
}

func (x *CmdGetManyByNameExt) Reset() {
	*x = CmdGetManyByNameExt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_get_many_by_name_ext_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdGetManyByNameExt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdGetManyByNameExt) ProtoMessage() {}

func (x *CmdGetManyByNameExt) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_get_many_by_name_ext_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdGetManyByNameExt.ProtoReflect.Descriptor instead.
func (*CmdGetManyByNameExt) Descriptor() ([]byte, []int) {
	return file_cmd_get_many_by_name_ext_proto_rawDescGZIP(), []int{0}
}

func (x *CmdGetManyByNameExt) GetMessageType() CmdType {
	if x != nil {
		return x.MessageType
	}
	return CmdType_CMD_UNDEFINED
}

func (x *CmdGetManyByNameExt) GetMessageVersion() int32 {
	if x != nil {
		return x.MessageVersion
	}
	return 0
}

func (x *CmdGetManyByNameExt) GetArgumentFlags() int32 {
	if x != nil {
		return x.ArgumentFlags
	}
	return 0
}

func (x *CmdGetManyByNameExt) GetMaxTradeIds() int32 {
	if x != nil {
		return x.MaxTradeIds
	}
	return 0
}

func (x *CmdGetManyByNameExt) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CmdGetManyByNameExt) GetSecurityNames() []string {
	if x != nil {
		return x.SecurityNames
	}
	return nil
}

type CmdGetManyByNameExtResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count uint32                                         `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Resp  []*CmdGetManyByNameExtResponse_ResponseMessage `protobuf:"bytes,2,rep,name=resp,proto3" json:"resp,omitempty"`
}

func (x *CmdGetManyByNameExtResponse) Reset() {
	*x = CmdGetManyByNameExtResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_get_many_by_name_ext_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdGetManyByNameExtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdGetManyByNameExtResponse) ProtoMessage() {}

func (x *CmdGetManyByNameExtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_get_many_by_name_ext_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdGetManyByNameExtResponse.ProtoReflect.Descriptor instead.
func (*CmdGetManyByNameExtResponse) Descriptor() ([]byte, []int) {
	return file_cmd_get_many_by_name_ext_proto_rawDescGZIP(), []int{1}
}

func (x *CmdGetManyByNameExtResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CmdGetManyByNameExtResponse) GetResp() []*CmdGetManyByNameExtResponse_ResponseMessage {
	if x != nil {
		return x.Resp
	}
	return nil
}

type CmdGetManyByNameExtResponseStream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to RequestResponse:
	//	*CmdGetManyByNameExtResponseStream_MsgOnSuccess_
	//	*CmdGetManyByNameExtResponseStream_MsgOnFailure_
	RequestResponse isCmdGetManyByNameExtResponseStream_RequestResponse `protobuf_oneof:"RequestResponse"`
}

func (x *CmdGetManyByNameExtResponseStream) Reset() {
	*x = CmdGetManyByNameExtResponseStream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_get_many_by_name_ext_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdGetManyByNameExtResponseStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdGetManyByNameExtResponseStream) ProtoMessage() {}

func (x *CmdGetManyByNameExtResponseStream) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_get_many_by_name_ext_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdGetManyByNameExtResponseStream.ProtoReflect.Descriptor instead.
func (*CmdGetManyByNameExtResponseStream) Descriptor() ([]byte, []int) {
	return file_cmd_get_many_by_name_ext_proto_rawDescGZIP(), []int{2}
}

func (m *CmdGetManyByNameExtResponseStream) GetRequestResponse() isCmdGetManyByNameExtResponseStream_RequestResponse {
	if m != nil {
		return m.RequestResponse
	}
	return nil
}

func (x *CmdGetManyByNameExtResponseStream) GetMsgOnSuccess() *CmdGetManyByNameExtResponseStream_MsgOnSuccess {
	if x, ok := x.GetRequestResponse().(*CmdGetManyByNameExtResponseStream_MsgOnSuccess_); ok {
		return x.MsgOnSuccess
	}
	return nil
}

func (x *CmdGetManyByNameExtResponseStream) GetMsgOnFailure() *CmdGetManyByNameExtResponseStream_MsgOnFailure {
	if x, ok := x.GetRequestResponse().(*CmdGetManyByNameExtResponseStream_MsgOnFailure_); ok {
		return x.MsgOnFailure
	}
	return nil
}

type isCmdGetManyByNameExtResponseStream_RequestResponse interface {
	isCmdGetManyByNameExtResponseStream_RequestResponse()
}

type CmdGetManyByNameExtResponseStream_MsgOnSuccess_ struct {
	MsgOnSuccess *CmdGetManyByNameExtResponseStream_MsgOnSuccess `protobuf:"bytes,2,opt,name=msg_on_success,json=msgOnSuccess,proto3,oneof"`
}

type CmdGetManyByNameExtResponseStream_MsgOnFailure_ struct {
	MsgOnFailure *CmdGetManyByNameExtResponseStream_MsgOnFailure `protobuf:"bytes,3,opt,name=msg_on_failure,json=msgOnFailure,proto3,oneof"`
}

func (*CmdGetManyByNameExtResponseStream_MsgOnSuccess_) isCmdGetManyByNameExtResponseStream_RequestResponse() {
}

func (*CmdGetManyByNameExtResponseStream_MsgOnFailure_) isCmdGetManyByNameExtResponseStream_RequestResponse() {
}

type CmdGetManyByNameExtResponse_ResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to RequestResponse:
	//	*CmdGetManyByNameExtResponse_ResponseMessage_MsgOnSuccess_
	//	*CmdGetManyByNameExtResponse_ResponseMessage_MsgOnFailure_
	RequestResponse isCmdGetManyByNameExtResponse_ResponseMessage_RequestResponse `protobuf_oneof:"RequestResponse"`
}

func (x *CmdGetManyByNameExtResponse_ResponseMessage) Reset() {
	*x = CmdGetManyByNameExtResponse_ResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_get_many_by_name_ext_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdGetManyByNameExtResponse_ResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdGetManyByNameExtResponse_ResponseMessage) ProtoMessage() {}

func (x *CmdGetManyByNameExtResponse_ResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_get_many_by_name_ext_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdGetManyByNameExtResponse_ResponseMessage.ProtoReflect.Descriptor instead.
func (*CmdGetManyByNameExtResponse_ResponseMessage) Descriptor() ([]byte, []int) {
	return file_cmd_get_many_by_name_ext_proto_rawDescGZIP(), []int{1, 0}
}

func (m *CmdGetManyByNameExtResponse_ResponseMessage) GetRequestResponse() isCmdGetManyByNameExtResponse_ResponseMessage_RequestResponse {
	if m != nil {
		return m.RequestResponse
	}
	return nil
}

func (x *CmdGetManyByNameExtResponse_ResponseMessage) GetMsgOnSuccess() *CmdGetManyByNameExtResponse_ResponseMessage_MsgOnSuccess {
	if x, ok := x.GetRequestResponse().(*CmdGetManyByNameExtResponse_ResponseMessage_MsgOnSuccess_); ok {
		return x.MsgOnSuccess
	}
	return nil
}

func (x *CmdGetManyByNameExtResponse_ResponseMessage) GetMsgOnFailure() *CmdGetManyByNameExtResponse_ResponseMessage_MsgOnFailure {
	if x, ok := x.GetRequestResponse().(*CmdGetManyByNameExtResponse_ResponseMessage_MsgOnFailure_); ok {
		return x.MsgOnFailure
	}
	return nil
}

type isCmdGetManyByNameExtResponse_ResponseMessage_RequestResponse interface {
	isCmdGetManyByNameExtResponse_ResponseMessage_RequestResponse()
}

type CmdGetManyByNameExtResponse_ResponseMessage_MsgOnSuccess_ struct {
	MsgOnSuccess *CmdGetManyByNameExtResponse_ResponseMessage_MsgOnSuccess `protobuf:"bytes,2,opt,name=msg_on_success,json=msgOnSuccess,proto3,oneof"`
}

type CmdGetManyByNameExtResponse_ResponseMessage_MsgOnFailure_ struct {
	MsgOnFailure *CmdGetManyByNameExtResponse_ResponseMessage_MsgOnFailure `protobuf:"bytes,3,opt,name=msg_on_failure,json=msgOnFailure,proto3,oneof"`
}

func (*CmdGetManyByNameExtResponse_ResponseMessage_MsgOnSuccess_) isCmdGetManyByNameExtResponse_ResponseMessage_RequestResponse() {
}

func (*CmdGetManyByNameExtResponse_ResponseMessage_MsgOnFailure_) isCmdGetManyByNameExtResponse_ResponseMessage_RequestResponse() {
}

type CmdGetManyByNameExtResponse_ResponseMessage_MsgOnSuccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasSucceeded bool      `protobuf:"varint,1,opt,name=has_succeeded,json=hasSucceeded,proto3" json:"has_succeeded,omitempty"`
	Metadata     *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	MemSize      uint32    `protobuf:"varint,3,opt,name=mem_size,json=memSize,proto3" json:"mem_size,omitempty"`
	Mem          []byte    `protobuf:"bytes,4,opt,name=mem,proto3" json:"mem,omitempty"`
}

func (x *CmdGetManyByNameExtResponse_ResponseMessage_MsgOnSuccess) Reset() {
	*x = CmdGetManyByNameExtResponse_ResponseMessage_MsgOnSuccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_get_many_by_name_ext_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdGetManyByNameExtResponse_ResponseMessage_MsgOnSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdGetManyByNameExtResponse_ResponseMessage_MsgOnSuccess) ProtoMessage() {}

func (x *CmdGetManyByNameExtResponse_ResponseMessage_MsgOnSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_get_many_by_name_ext_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdGetManyByNameExtResponse_ResponseMessage_MsgOnSuccess.ProtoReflect.Descriptor instead.
func (*CmdGetManyByNameExtResponse_ResponseMessage_MsgOnSuccess) Descriptor() ([]byte, []int) {
	return file_cmd_get_many_by_name_ext_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *CmdGetManyByNameExtResponse_ResponseMessage_MsgOnSuccess) GetHasSucceeded() bool {
	if x != nil {
		return x.HasSucceeded
	}
	return false
}

func (x *CmdGetManyByNameExtResponse_ResponseMessage_MsgOnSuccess) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CmdGetManyByNameExtResponse_ResponseMessage_MsgOnSuccess) GetMemSize() uint32 {
	if x != nil {
		return x.MemSize
	}
	return 0
}

func (x *CmdGetManyByNameExtResponse_ResponseMessage_MsgOnSuccess) GetMem() []byte {
	if x != nil {
		return x.Mem
	}
	return nil
}

type CmdGetManyByNameExtResponse_ResponseMessage_MsgOnFailure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasSucceeded bool      `protobuf:"varint,1,opt,name=has_succeeded,json=hasSucceeded,proto3" json:"has_succeeded,omitempty"`
	ErrorType    ErrorType `protobuf:"varint,2,opt,name=error_type,json=errorType,proto3,enum=org.anonymous.grpc.ErrorType" json:"error_type,omitempty"`
	ErrorText    string    `protobuf:"bytes,3,opt,name=error_text,json=errorText,proto3" json:"error_text,omitempty"`
}

func (x *CmdGetManyByNameExtResponse_ResponseMessage_MsgOnFailure) Reset() {
	*x = CmdGetManyByNameExtResponse_ResponseMessage_MsgOnFailure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_get_many_by_name_ext_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdGetManyByNameExtResponse_ResponseMessage_MsgOnFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdGetManyByNameExtResponse_ResponseMessage_MsgOnFailure) ProtoMessage() {}

func (x *CmdGetManyByNameExtResponse_ResponseMessage_MsgOnFailure) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_get_many_by_name_ext_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdGetManyByNameExtResponse_ResponseMessage_MsgOnFailure.ProtoReflect.Descriptor instead.
func (*CmdGetManyByNameExtResponse_ResponseMessage_MsgOnFailure) Descriptor() ([]byte, []int) {
	return file_cmd_get_many_by_name_ext_proto_rawDescGZIP(), []int{1, 0, 1}
}

func (x *CmdGetManyByNameExtResponse_ResponseMessage_MsgOnFailure) GetHasSucceeded() bool {
	if x != nil {
		return x.HasSucceeded
	}
	return false
}

func (x *CmdGetManyByNameExtResponse_ResponseMessage_MsgOnFailure) GetErrorType() ErrorType {
	if x != nil {
		return x.ErrorType
	}
	return ErrorType_ERR_INVALID_ARGUMENTS
}

func (x *CmdGetManyByNameExtResponse_ResponseMessage_MsgOnFailure) GetErrorText() string {
	if x != nil {
		return x.ErrorText
	}
	return ""
}

type CmdGetManyByNameExtResponseStream_MsgOnSuccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasSucceeded bool      `protobuf:"varint,1,opt,name=has_succeeded,json=hasSucceeded,proto3" json:"has_succeeded,omitempty"`
	Metadata     *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	MemSize      uint32    `protobuf:"varint,3,opt,name=mem_size,json=memSize,proto3" json:"mem_size,omitempty"`
	Mem          []byte    `protobuf:"bytes,4,opt,name=mem,proto3" json:"mem,omitempty"`
}

func (x *CmdGetManyByNameExtResponseStream_MsgOnSuccess) Reset() {
	*x = CmdGetManyByNameExtResponseStream_MsgOnSuccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_get_many_by_name_ext_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdGetManyByNameExtResponseStream_MsgOnSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdGetManyByNameExtResponseStream_MsgOnSuccess) ProtoMessage() {}

func (x *CmdGetManyByNameExtResponseStream_MsgOnSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_get_many_by_name_ext_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdGetManyByNameExtResponseStream_MsgOnSuccess.ProtoReflect.Descriptor instead.
func (*CmdGetManyByNameExtResponseStream_MsgOnSuccess) Descriptor() ([]byte, []int) {
	return file_cmd_get_many_by_name_ext_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CmdGetManyByNameExtResponseStream_MsgOnSuccess) GetHasSucceeded() bool {
	if x != nil {
		return x.HasSucceeded
	}
	return false
}

func (x *CmdGetManyByNameExtResponseStream_MsgOnSuccess) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CmdGetManyByNameExtResponseStream_MsgOnSuccess) GetMemSize() uint32 {
	if x != nil {
		return x.MemSize
	}
	return 0
}

func (x *CmdGetManyByNameExtResponseStream_MsgOnSuccess) GetMem() []byte {
	if x != nil {
		return x.Mem
	}
	return nil
}

type CmdGetManyByNameExtResponseStream_MsgOnFailure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasSucceeded bool      `protobuf:"varint,1,opt,name=has_succeeded,json=hasSucceeded,proto3" json:"has_succeeded,omitempty"`
	ErrorType    ErrorType `protobuf:"varint,2,opt,name=error_type,json=errorType,proto3,enum=org.anonymous.grpc.ErrorType" json:"error_type,omitempty"`
	ErrorText    string    `protobuf:"bytes,3,opt,name=error_text,json=errorText,proto3" json:"error_text,omitempty"`
}

func (x *CmdGetManyByNameExtResponseStream_MsgOnFailure) Reset() {
	*x = CmdGetManyByNameExtResponseStream_MsgOnFailure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_get_many_by_name_ext_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdGetManyByNameExtResponseStream_MsgOnFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdGetManyByNameExtResponseStream_MsgOnFailure) ProtoMessage() {}

func (x *CmdGetManyByNameExtResponseStream_MsgOnFailure) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_get_many_by_name_ext_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdGetManyByNameExtResponseStream_MsgOnFailure.ProtoReflect.Descriptor instead.
func (*CmdGetManyByNameExtResponseStream_MsgOnFailure) Descriptor() ([]byte, []int) {
	return file_cmd_get_many_by_name_ext_proto_rawDescGZIP(), []int{2, 1}
}

func (x *CmdGetManyByNameExtResponseStream_MsgOnFailure) GetHasSucceeded() bool {
	if x != nil {
		return x.HasSucceeded
	}
	return false
}

func (x *CmdGetManyByNameExtResponseStream_MsgOnFailure) GetErrorType() ErrorType {
	if x != nil {
		return x.ErrorType
	}
	return ErrorType_ERR_INVALID_ARGUMENTS
}

func (x *CmdGetManyByNameExtResponseStream_MsgOnFailure) GetErrorText() string {
	if x != nil {
		return x.ErrorText
	}
	return ""
}

var File_cmd_get_many_by_name_ext_proto protoreflect.FileDescriptor

var file_cmd_get_many_by_name_ext_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x63, 0x6d, 0x64, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x6d, 0x61, 0x6e, 0x79, 0x5f, 0x62,
	0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x12, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x1a, 0x10, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x63, 0x6d, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x86, 0x02, 0x0a, 0x13, 0x43, 0x6d, 0x64, 0x47, 0x65,
	0x74, 0x4d, 0x61, 0x6e, 0x79, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x45, 0x78, 0x74, 0x12, 0x3e,
	0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x6e, 0x6f, 0x6e, 0x79,
	0x6d, 0x6f, 0x75, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6d, 0x64, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x27,
	0x0a, 0x0f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x72, 0x67, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0d, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x22,
	0x0a, 0x0d, 0x6d, 0x61, 0x78, 0x5f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x54, 0x72, 0x61, 0x64, 0x65, 0x49,
	0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x63, 0x75,
	0x72, 0x69, 0x74, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0d, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22,
	0xcb, 0x05, 0x0a, 0x1b, 0x43, 0x6d, 0x64, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x79, 0x42, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x45, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x53, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d,
	0x6f, 0x75, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6d, 0x64, 0x47, 0x65, 0x74, 0x4d,
	0x61, 0x6e, 0x79, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x45, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x1a, 0xc0, 0x04, 0x0a, 0x0f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x74,
	0x0a, 0x0e, 0x6d, 0x73, 0x67, 0x5f, 0x6f, 0x6e, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x4c, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x6e, 0x6f,
	0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6d, 0x64, 0x47,
	0x65, 0x74, 0x4d, 0x61, 0x6e, 0x79, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x45, 0x78, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x73, 0x67, 0x4f, 0x6e, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x0c, 0x6d, 0x73, 0x67, 0x4f, 0x6e, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x74, 0x0a, 0x0e, 0x6d, 0x73, 0x67, 0x5f, 0x6f, 0x6e, 0x5f, 0x66,
	0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x4c, 0x2e, 0x6f,
	0x72, 0x67, 0x2e, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x43, 0x6d, 0x64, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x79, 0x42, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x45, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x73,
	0x67, 0x4f, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x6d, 0x73,
	0x67, 0x4f, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x1a, 0x9a, 0x01, 0x0a, 0x0c, 0x4d,
	0x73, 0x67, 0x4f, 0x6e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x68,
	0x61, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0c, 0x68, 0x61, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x65, 0x64,
	0x12, 0x38, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f,
	0x75, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x65,
	0x6d, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6d, 0x65,
	0x6d, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x65, 0x6d, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x6d, 0x65, 0x6d, 0x1a, 0x90, 0x01, 0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x4f,
	0x6e, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x68, 0x61, 0x73, 0x5f,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0c, 0x68, 0x61, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x65, 0x64, 0x12, 0x3c, 0x0a,
	0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1d, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75,
	0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x65, 0x78, 0x74, 0x42, 0x11, 0x0a, 0x0f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xbe, 0x04,
	0x0a, 0x21, 0x43, 0x6d, 0x64, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x79, 0x42, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x45, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x12, 0x6a, 0x0a, 0x0e, 0x6d, 0x73, 0x67, 0x5f, 0x6f, 0x6e, 0x5f, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x42, 0x2e, 0x6f, 0x72,
	0x67, 0x2e, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x43, 0x6d, 0x64, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x79, 0x42, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x45, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x2e, 0x4d, 0x73, 0x67, 0x4f, 0x6e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x48,
	0x00, 0x52, 0x0c, 0x6d, 0x73, 0x67, 0x4f, 0x6e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x6a, 0x0a, 0x0e, 0x6d, 0x73, 0x67, 0x5f, 0x6f, 0x6e, 0x5f, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x42, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x6e,
	0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6d, 0x64,
	0x47, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x79, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x45, 0x78, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x4d,
	0x73, 0x67, 0x4f, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x6d,
	0x73, 0x67, 0x4f, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x1a, 0x9a, 0x01, 0x0a, 0x0c,
	0x4d, 0x73, 0x67, 0x4f, 0x6e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x23, 0x0a, 0x0d,
	0x68, 0x61, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0c, 0x68, 0x61, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x65,
	0x64, 0x12, 0x38, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d,
	0x6f, 0x75, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x6d,
	0x65, 0x6d, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6d,
	0x65, 0x6d, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x65, 0x6d, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x65, 0x6d, 0x1a, 0x90, 0x01, 0x0a, 0x0c, 0x4d, 0x73, 0x67,
	0x4f, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x68, 0x61, 0x73,
	0x5f, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0c, 0x68, 0x61, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x65, 0x64, 0x12, 0x3c,
	0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f,
	0x75, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x65, 0x78, 0x74, 0x42, 0x11, 0x0a, 0x0f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3c,
	0x50, 0x01, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73,
	0x6f, 0x6d, 0x6e, 0x61, 0x74, 0x68, 0x36, 0x37, 0x36, 0x34, 0x33, 0x2f, 0x61, 0x75, 0x72, 0x6f,
	0x72, 0x61, 0x2d, 0x73, 0x69, 0x7a, 0x69, 0x6e, 0x67, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x67, 0x6f, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_get_many_by_name_ext_proto_rawDescOnce sync.Once
	file_cmd_get_many_by_name_ext_proto_rawDescData = file_cmd_get_many_by_name_ext_proto_rawDesc
)

func file_cmd_get_many_by_name_ext_proto_rawDescGZIP() []byte {
	file_cmd_get_many_by_name_ext_proto_rawDescOnce.Do(func() {
		file_cmd_get_many_by_name_ext_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_get_many_by_name_ext_proto_rawDescData)
	})
	return file_cmd_get_many_by_name_ext_proto_rawDescData
}

var file_cmd_get_many_by_name_ext_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cmd_get_many_by_name_ext_proto_goTypes = []interface{}{
	(*CmdGetManyByNameExt)(nil),                                      // 0: org.anonymous.grpc.CmdGetManyByNameExt
	(*CmdGetManyByNameExtResponse)(nil),                              // 1: org.anonymous.grpc.CmdGetManyByNameExtResponse
	(*CmdGetManyByNameExtResponseStream)(nil),                        // 2: org.anonymous.grpc.CmdGetManyByNameExtResponseStream
	(*CmdGetManyByNameExtResponse_ResponseMessage)(nil),              // 3: org.anonymous.grpc.CmdGetManyByNameExtResponse.ResponseMessage
	(*CmdGetManyByNameExtResponse_ResponseMessage_MsgOnSuccess)(nil), // 4: org.anonymous.grpc.CmdGetManyByNameExtResponse.ResponseMessage.MsgOnSuccess
	(*CmdGetManyByNameExtResponse_ResponseMessage_MsgOnFailure)(nil), // 5: org.anonymous.grpc.CmdGetManyByNameExtResponse.ResponseMessage.MsgOnFailure
	(*CmdGetManyByNameExtResponseStream_MsgOnSuccess)(nil),           // 6: org.anonymous.grpc.CmdGetManyByNameExtResponseStream.MsgOnSuccess
	(*CmdGetManyByNameExtResponseStream_MsgOnFailure)(nil),           // 7: org.anonymous.grpc.CmdGetManyByNameExtResponseStream.MsgOnFailure
	(CmdType)(0),     // 8: org.anonymous.grpc.CmdType
	(*Metadata)(nil), // 9: org.anonymous.grpc.Metadata
	(ErrorType)(0),   // 10: org.anonymous.grpc.ErrorType
}
var file_cmd_get_many_by_name_ext_proto_depIdxs = []int32{
	8,  // 0: org.anonymous.grpc.CmdGetManyByNameExt.message_type:type_name -> org.anonymous.grpc.CmdType
	3,  // 1: org.anonymous.grpc.CmdGetManyByNameExtResponse.resp:type_name -> org.anonymous.grpc.CmdGetManyByNameExtResponse.ResponseMessage
	6,  // 2: org.anonymous.grpc.CmdGetManyByNameExtResponseStream.msg_on_success:type_name -> org.anonymous.grpc.CmdGetManyByNameExtResponseStream.MsgOnSuccess
	7,  // 3: org.anonymous.grpc.CmdGetManyByNameExtResponseStream.msg_on_failure:type_name -> org.anonymous.grpc.CmdGetManyByNameExtResponseStream.MsgOnFailure
	4,  // 4: org.anonymous.grpc.CmdGetManyByNameExtResponse.ResponseMessage.msg_on_success:type_name -> org.anonymous.grpc.CmdGetManyByNameExtResponse.ResponseMessage.MsgOnSuccess
	5,  // 5: org.anonymous.grpc.CmdGetManyByNameExtResponse.ResponseMessage.msg_on_failure:type_name -> org.anonymous.grpc.CmdGetManyByNameExtResponse.ResponseMessage.MsgOnFailure
	9,  // 6: org.anonymous.grpc.CmdGetManyByNameExtResponse.ResponseMessage.MsgOnSuccess.metadata:type_name -> org.anonymous.grpc.Metadata
	10, // 7: org.anonymous.grpc.CmdGetManyByNameExtResponse.ResponseMessage.MsgOnFailure.error_type:type_name -> org.anonymous.grpc.ErrorType
	9,  // 8: org.anonymous.grpc.CmdGetManyByNameExtResponseStream.MsgOnSuccess.metadata:type_name -> org.anonymous.grpc.Metadata
	10, // 9: org.anonymous.grpc.CmdGetManyByNameExtResponseStream.MsgOnFailure.error_type:type_name -> org.anonymous.grpc.ErrorType
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_cmd_get_many_by_name_ext_proto_init() }
func file_cmd_get_many_by_name_ext_proto_init() {
	if File_cmd_get_many_by_name_ext_proto != nil {
		return
	}
	file_error_type_proto_init()
	file_metadata_proto_init()
	file_cmd_type_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cmd_get_many_by_name_ext_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdGetManyByNameExt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_get_many_by_name_ext_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdGetManyByNameExtResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_get_many_by_name_ext_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdGetManyByNameExtResponseStream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_get_many_by_name_ext_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdGetManyByNameExtResponse_ResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_get_many_by_name_ext_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdGetManyByNameExtResponse_ResponseMessage_MsgOnSuccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_get_many_by_name_ext_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdGetManyByNameExtResponse_ResponseMessage_MsgOnFailure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_get_many_by_name_ext_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdGetManyByNameExtResponseStream_MsgOnSuccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_get_many_by_name_ext_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdGetManyByNameExtResponseStream_MsgOnFailure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cmd_get_many_by_name_ext_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*CmdGetManyByNameExtResponseStream_MsgOnSuccess_)(nil),
		(*CmdGetManyByNameExtResponseStream_MsgOnFailure_)(nil),
	}
	file_cmd_get_many_by_name_ext_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*CmdGetManyByNameExtResponse_ResponseMessage_MsgOnSuccess_)(nil),
		(*CmdGetManyByNameExtResponse_ResponseMessage_MsgOnFailure_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_get_many_by_name_ext_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_get_many_by_name_ext_proto_goTypes,
		DependencyIndexes: file_cmd_get_many_by_name_ext_proto_depIdxs,
		MessageInfos:      file_cmd_get_many_by_name_ext_proto_msgTypes,
	}.Build()
	File_cmd_get_many_by_name_ext_proto = out.File
	file_cmd_get_many_by_name_ext_proto_rawDesc = nil
	file_cmd_get_many_by_name_ext_proto_goTypes = nil
	file_cmd_get_many_by_name_ext_proto_depIdxs = nil
}
