// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: cmd_get_by_name_ext.proto

package baseproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CmdGetByNameExt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgSize       int32   `protobuf:"varint,1,opt,name=msg_size,json=msgSize,proto3" json:"msg_size,omitempty"`
	MsgType       CmdType `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3,enum=org.anonymous.grpc.CmdType" json:"msg_type,omitempty"`
	ArgumentFlags int32   `protobuf:"varint,3,opt,name=argument_flags,json=argumentFlags,proto3" json:"argument_flags,omitempty"`
	SecurityName  string  `protobuf:"bytes,4,opt,name=security_name,json=securityName,proto3" json:"security_name,omitempty"`
}

func (x *CmdGetByNameExt) Reset() {
	*x = CmdGetByNameExt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_get_by_name_ext_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdGetByNameExt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdGetByNameExt) ProtoMessage() {}

func (x *CmdGetByNameExt) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_get_by_name_ext_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdGetByNameExt.ProtoReflect.Descriptor instead.
func (*CmdGetByNameExt) Descriptor() ([]byte, []int) {
	return file_cmd_get_by_name_ext_proto_rawDescGZIP(), []int{0}
}

func (x *CmdGetByNameExt) GetMsgSize() int32 {
	if x != nil {
		return x.MsgSize
	}
	return 0
}

func (x *CmdGetByNameExt) GetMsgType() CmdType {
	if x != nil {
		return x.MsgType
	}
	return CmdType_CMD_UNDEFINED
}

func (x *CmdGetByNameExt) GetArgumentFlags() int32 {
	if x != nil {
		return x.ArgumentFlags
	}
	return 0
}

func (x *CmdGetByNameExt) GetSecurityName() string {
	if x != nil {
		return x.SecurityName
	}
	return ""
}

type CmdGetByNameExtResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to RequestResponse:
	//	*CmdGetByNameExtResponse_MsgOnSuccess_
	//	*CmdGetByNameExtResponse_MsgOnFailure_
	RequestResponse isCmdGetByNameExtResponse_RequestResponse `protobuf_oneof:"RequestResponse"`
}

func (x *CmdGetByNameExtResponse) Reset() {
	*x = CmdGetByNameExtResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_get_by_name_ext_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdGetByNameExtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdGetByNameExtResponse) ProtoMessage() {}

func (x *CmdGetByNameExtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_get_by_name_ext_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdGetByNameExtResponse.ProtoReflect.Descriptor instead.
func (*CmdGetByNameExtResponse) Descriptor() ([]byte, []int) {
	return file_cmd_get_by_name_ext_proto_rawDescGZIP(), []int{1}
}

func (m *CmdGetByNameExtResponse) GetRequestResponse() isCmdGetByNameExtResponse_RequestResponse {
	if m != nil {
		return m.RequestResponse
	}
	return nil
}

func (x *CmdGetByNameExtResponse) GetMsgOnSuccess() *CmdGetByNameExtResponse_MsgOnSuccess {
	if x, ok := x.GetRequestResponse().(*CmdGetByNameExtResponse_MsgOnSuccess_); ok {
		return x.MsgOnSuccess
	}
	return nil
}

func (x *CmdGetByNameExtResponse) GetMsgOnFailure() *CmdGetByNameExtResponse_MsgOnFailure {
	if x, ok := x.GetRequestResponse().(*CmdGetByNameExtResponse_MsgOnFailure_); ok {
		return x.MsgOnFailure
	}
	return nil
}

type isCmdGetByNameExtResponse_RequestResponse interface {
	isCmdGetByNameExtResponse_RequestResponse()
}

type CmdGetByNameExtResponse_MsgOnSuccess_ struct {
	MsgOnSuccess *CmdGetByNameExtResponse_MsgOnSuccess `protobuf:"bytes,2,opt,name=msg_on_success,json=msgOnSuccess,proto3,oneof"`
}

type CmdGetByNameExtResponse_MsgOnFailure_ struct {
	MsgOnFailure *CmdGetByNameExtResponse_MsgOnFailure `protobuf:"bytes,3,opt,name=msg_on_failure,json=msgOnFailure,proto3,oneof"`
}

func (*CmdGetByNameExtResponse_MsgOnSuccess_) isCmdGetByNameExtResponse_RequestResponse() {}

func (*CmdGetByNameExtResponse_MsgOnFailure_) isCmdGetByNameExtResponse_RequestResponse() {}

type CmdGetByNameExtResponse_MsgOnSuccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasSucceeded bool      `protobuf:"varint,1,opt,name=has_succeeded,json=hasSucceeded,proto3" json:"has_succeeded,omitempty"`
	Metadata     *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	MemSize      uint32    `protobuf:"varint,3,opt,name=mem_size,json=memSize,proto3" json:"mem_size,omitempty"`
	Mem          []byte    `protobuf:"bytes,4,opt,name=mem,proto3" json:"mem,omitempty"`
}

func (x *CmdGetByNameExtResponse_MsgOnSuccess) Reset() {
	*x = CmdGetByNameExtResponse_MsgOnSuccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_get_by_name_ext_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdGetByNameExtResponse_MsgOnSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdGetByNameExtResponse_MsgOnSuccess) ProtoMessage() {}

func (x *CmdGetByNameExtResponse_MsgOnSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_get_by_name_ext_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdGetByNameExtResponse_MsgOnSuccess.ProtoReflect.Descriptor instead.
func (*CmdGetByNameExtResponse_MsgOnSuccess) Descriptor() ([]byte, []int) {
	return file_cmd_get_by_name_ext_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CmdGetByNameExtResponse_MsgOnSuccess) GetHasSucceeded() bool {
	if x != nil {
		return x.HasSucceeded
	}
	return false
}

func (x *CmdGetByNameExtResponse_MsgOnSuccess) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CmdGetByNameExtResponse_MsgOnSuccess) GetMemSize() uint32 {
	if x != nil {
		return x.MemSize
	}
	return 0
}

func (x *CmdGetByNameExtResponse_MsgOnSuccess) GetMem() []byte {
	if x != nil {
		return x.Mem
	}
	return nil
}

type CmdGetByNameExtResponse_MsgOnFailure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasSucceeded bool      `protobuf:"varint,1,opt,name=has_succeeded,json=hasSucceeded,proto3" json:"has_succeeded,omitempty"`
	ErrorType    ErrorType `protobuf:"varint,2,opt,name=error_type,json=errorType,proto3,enum=org.anonymous.grpc.ErrorType" json:"error_type,omitempty"`
	ErrorText    string    `protobuf:"bytes,3,opt,name=error_text,json=errorText,proto3" json:"error_text,omitempty"`
}

func (x *CmdGetByNameExtResponse_MsgOnFailure) Reset() {
	*x = CmdGetByNameExtResponse_MsgOnFailure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_get_by_name_ext_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdGetByNameExtResponse_MsgOnFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdGetByNameExtResponse_MsgOnFailure) ProtoMessage() {}

func (x *CmdGetByNameExtResponse_MsgOnFailure) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_get_by_name_ext_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdGetByNameExtResponse_MsgOnFailure.ProtoReflect.Descriptor instead.
func (*CmdGetByNameExtResponse_MsgOnFailure) Descriptor() ([]byte, []int) {
	return file_cmd_get_by_name_ext_proto_rawDescGZIP(), []int{1, 1}
}

func (x *CmdGetByNameExtResponse_MsgOnFailure) GetHasSucceeded() bool {
	if x != nil {
		return x.HasSucceeded
	}
	return false
}

func (x *CmdGetByNameExtResponse_MsgOnFailure) GetErrorType() ErrorType {
	if x != nil {
		return x.ErrorType
	}
	return ErrorType_ERR_INVALID_ARGUMENTS
}

func (x *CmdGetByNameExtResponse_MsgOnFailure) GetErrorText() string {
	if x != nil {
		return x.ErrorText
	}
	return ""
}

var File_cmd_get_by_name_ext_proto protoreflect.FileDescriptor

var file_cmd_get_by_name_ext_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x6d, 0x64, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x62, 0x79, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x5f, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6f, 0x72, 0x67,
	0x2e, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x1a,
	0x10, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0e, 0x63, 0x6d, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xb0, 0x01, 0x0a, 0x0f, 0x43, 0x6d, 0x64, 0x47, 0x65, 0x74, 0x42, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x45, 0x78, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x36, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f,
	0x75, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6d, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x72, 0x67, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0d, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x12,
	0x23, 0x0a, 0x0d, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0xa0, 0x04, 0x0a, 0x17, 0x43, 0x6d, 0x64, 0x47, 0x65, 0x74, 0x42,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x45, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x60, 0x0a, 0x0e, 0x6d, 0x73, 0x67, 0x5f, 0x6f, 0x6e, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61,
	0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6d,
	0x64, 0x47, 0x65, 0x74, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x45, 0x78, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x73, 0x67, 0x4f, 0x6e, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x48, 0x00, 0x52, 0x0c, 0x6d, 0x73, 0x67, 0x4f, 0x6e, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x60, 0x0a, 0x0e, 0x6d, 0x73, 0x67, 0x5f, 0x6f, 0x6e, 0x5f, 0x66, 0x61, 0x69,
	0x6c, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x6f, 0x72, 0x67,
	0x2e, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x43, 0x6d, 0x64, 0x47, 0x65, 0x74, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x45, 0x78, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x73, 0x67, 0x4f, 0x6e, 0x46, 0x61, 0x69,
	0x6c, 0x75, 0x72, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x6d, 0x73, 0x67, 0x4f, 0x6e, 0x46, 0x61, 0x69,
	0x6c, 0x75, 0x72, 0x65, 0x1a, 0x9a, 0x01, 0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x4f, 0x6e, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x68, 0x61, 0x73, 0x5f, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x65, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x68, 0x61,
	0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x65, 0x64, 0x12, 0x38, 0x0a, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f,
	0x72, 0x67, 0x2e, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x65, 0x6d, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x65, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x65,
	0x6d, 0x1a, 0x90, 0x01, 0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x4f, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x75,
	0x72, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x68, 0x61, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65,
	0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x68, 0x61, 0x73, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x65, 0x64, 0x65, 0x64, 0x12, 0x3c, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6f, 0x72,
	0x67, 0x2e, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x54, 0x65, 0x78, 0x74, 0x42, 0x11, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3c, 0x50, 0x01, 0x5a, 0x38, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x6d, 0x6e, 0x61, 0x74, 0x68, 0x36,
	0x37, 0x36, 0x34, 0x33, 0x2f, 0x61, 0x75, 0x72, 0x6f, 0x72, 0x61, 0x2d, 0x73, 0x69, 0x7a, 0x69,
	0x6e, 0x67, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x67, 0x6f, 0x2f, 0x62, 0x61, 0x73, 0x65,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_get_by_name_ext_proto_rawDescOnce sync.Once
	file_cmd_get_by_name_ext_proto_rawDescData = file_cmd_get_by_name_ext_proto_rawDesc
)

func file_cmd_get_by_name_ext_proto_rawDescGZIP() []byte {
	file_cmd_get_by_name_ext_proto_rawDescOnce.Do(func() {
		file_cmd_get_by_name_ext_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_get_by_name_ext_proto_rawDescData)
	})
	return file_cmd_get_by_name_ext_proto_rawDescData
}

var file_cmd_get_by_name_ext_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cmd_get_by_name_ext_proto_goTypes = []interface{}{
	(*CmdGetByNameExt)(nil),                      // 0: org.anonymous.grpc.CmdGetByNameExt
	(*CmdGetByNameExtResponse)(nil),              // 1: org.anonymous.grpc.CmdGetByNameExtResponse
	(*CmdGetByNameExtResponse_MsgOnSuccess)(nil), // 2: org.anonymous.grpc.CmdGetByNameExtResponse.MsgOnSuccess
	(*CmdGetByNameExtResponse_MsgOnFailure)(nil), // 3: org.anonymous.grpc.CmdGetByNameExtResponse.MsgOnFailure
	(CmdType)(0),     // 4: org.anonymous.grpc.CmdType
	(*Metadata)(nil), // 5: org.anonymous.grpc.Metadata
	(ErrorType)(0),   // 6: org.anonymous.grpc.ErrorType
}
var file_cmd_get_by_name_ext_proto_depIdxs = []int32{
	4, // 0: org.anonymous.grpc.CmdGetByNameExt.msg_type:type_name -> org.anonymous.grpc.CmdType
	2, // 1: org.anonymous.grpc.CmdGetByNameExtResponse.msg_on_success:type_name -> org.anonymous.grpc.CmdGetByNameExtResponse.MsgOnSuccess
	3, // 2: org.anonymous.grpc.CmdGetByNameExtResponse.msg_on_failure:type_name -> org.anonymous.grpc.CmdGetByNameExtResponse.MsgOnFailure
	5, // 3: org.anonymous.grpc.CmdGetByNameExtResponse.MsgOnSuccess.metadata:type_name -> org.anonymous.grpc.Metadata
	6, // 4: org.anonymous.grpc.CmdGetByNameExtResponse.MsgOnFailure.error_type:type_name -> org.anonymous.grpc.ErrorType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cmd_get_by_name_ext_proto_init() }
func file_cmd_get_by_name_ext_proto_init() {
	if File_cmd_get_by_name_ext_proto != nil {
		return
	}
	file_error_type_proto_init()
	file_metadata_proto_init()
	file_cmd_type_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cmd_get_by_name_ext_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdGetByNameExt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_get_by_name_ext_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdGetByNameExtResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_get_by_name_ext_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdGetByNameExtResponse_MsgOnSuccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_get_by_name_ext_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdGetByNameExtResponse_MsgOnFailure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cmd_get_by_name_ext_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*CmdGetByNameExtResponse_MsgOnSuccess_)(nil),
		(*CmdGetByNameExtResponse_MsgOnFailure_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_get_by_name_ext_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_get_by_name_ext_proto_goTypes,
		DependencyIndexes: file_cmd_get_by_name_ext_proto_depIdxs,
		MessageInfos:      file_cmd_get_by_name_ext_proto_msgTypes,
	}.Build()
	File_cmd_get_by_name_ext_proto = out.File
	file_cmd_get_by_name_ext_proto_rawDesc = nil
	file_cmd_get_by_name_ext_proto_goTypes = nil
	file_cmd_get_by_name_ext_proto_depIdxs = nil
}
