// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: cmd_trans_type.proto

package baseproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransType int32

const (
	TransType_HEADER  TransType = 0
	TransType_INSERT  TransType = 1
	TransType_UPDATE  TransType = 2
	TransType_RENAME  TransType = 3
	TransType_DELETE  TransType = 4
	TransType_TRAILER TransType = 5
)

// Enum value maps for TransType.
var (
	TransType_name = map[int32]string{
		0: "HEADER",
		1: "INSERT",
		2: "UPDATE",
		3: "RENAME",
		4: "DELETE",
		5: "TRAILER",
	}
	TransType_value = map[string]int32{
		"HEADER":  0,
		"INSERT":  1,
		"UPDATE":  2,
		"RENAME":  3,
		"DELETE":  4,
		"TRAILER": 5,
	}
)

func (x TransType) Enum() *TransType {
	p := new(TransType)
	*p = x
	return p
}

func (x TransType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransType) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_trans_type_proto_enumTypes[0].Descriptor()
}

func (TransType) Type() protoreflect.EnumType {
	return &file_cmd_trans_type_proto_enumTypes[0]
}

func (x TransType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransType.Descriptor instead.
func (TransType) EnumDescriptor() ([]byte, []int) {
	return file_cmd_trans_type_proto_rawDescGZIP(), []int{0}
}

var File_cmd_trans_type_proto protoreflect.FileDescriptor

var file_cmd_trans_type_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6d, 0x64, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x6e, 0x6f, 0x6e,
	0x79, 0x6d, 0x6f, 0x75, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2a, 0x54, 0x0a, 0x09, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x48, 0x45, 0x41, 0x44, 0x45,
	0x52, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x4e, 0x53, 0x45, 0x52, 0x54, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x52,
	0x45, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54,
	0x45, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x52, 0x41, 0x49, 0x4c, 0x45, 0x52, 0x10, 0x05,
	0x42, 0x3c, 0x50, 0x01, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x6f, 0x6d, 0x6e, 0x61, 0x74, 0x68, 0x36, 0x37, 0x36, 0x34, 0x33, 0x2f, 0x61, 0x75,
	0x72, 0x6f, 0x72, 0x61, 0x2d, 0x73, 0x69, 0x7a, 0x69, 0x6e, 0x67, 0x2f, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x67, 0x6f, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_trans_type_proto_rawDescOnce sync.Once
	file_cmd_trans_type_proto_rawDescData = file_cmd_trans_type_proto_rawDesc
)

func file_cmd_trans_type_proto_rawDescGZIP() []byte {
	file_cmd_trans_type_proto_rawDescOnce.Do(func() {
		file_cmd_trans_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_trans_type_proto_rawDescData)
	})
	return file_cmd_trans_type_proto_rawDescData
}

var file_cmd_trans_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmd_trans_type_proto_goTypes = []interface{}{
	(TransType)(0), // 0: org.anonymous.grpc.TransType
}
var file_cmd_trans_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_trans_type_proto_init() }
func file_cmd_trans_type_proto_init() {
	if File_cmd_trans_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_trans_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_trans_type_proto_goTypes,
		DependencyIndexes: file_cmd_trans_type_proto_depIdxs,
		EnumInfos:         file_cmd_trans_type_proto_enumTypes,
	}.Build()
	File_cmd_trans_type_proto = out.File
	file_cmd_trans_type_proto_rawDesc = nil
	file_cmd_trans_type_proto_goTypes = nil
	file_cmd_trans_type_proto_depIdxs = nil
}
