// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package baseproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ObjectServiceClient is the client API for ObjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ObjectServiceClient interface {
	Exists(ctx context.Context, in *ObjectRequest, opts ...grpc.CallOption) (*ObjectResponse, error)
}

type objectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewObjectServiceClient(cc grpc.ClientConnInterface) ObjectServiceClient {
	return &objectServiceClient{cc}
}

var objectServiceExistsStreamDesc = &grpc.StreamDesc{
	StreamName: "exists",
}

func (c *objectServiceClient) Exists(ctx context.Context, in *ObjectRequest, opts ...grpc.CallOption) (*ObjectResponse, error) {
	out := new(ObjectResponse)
	err := c.cc.Invoke(ctx, "/org.anonymous.grpc.ObjectService/exists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObjectServiceService is the service API for ObjectService service.
// Fields should be assigned to their respective handler implementations only before
// RegisterObjectServiceService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type ObjectServiceService struct {
	Exists func(context.Context, *ObjectRequest) (*ObjectResponse, error)
}

func (s *ObjectServiceService) exists(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Exists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/org.anonymous.grpc.ObjectService/Exists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Exists(ctx, req.(*ObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterObjectServiceService registers a service implementation with a gRPC server.
func RegisterObjectServiceService(s grpc.ServiceRegistrar, srv *ObjectServiceService) {
	srvCopy := *srv
	if srvCopy.Exists == nil {
		srvCopy.Exists = func(context.Context, *ObjectRequest) (*ObjectResponse, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Exists not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "org.anonymous.grpc.ObjectService",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "exists",
				Handler:    srvCopy.exists,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "ObjectService.proto",
	}

	s.RegisterService(&sd, nil)
}
